In [6]:
#Q1. .Write a code to combine  a one and a two-dimensional NumPy Array
import numpy as np
  
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
  


One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
#Q2.  Write a code to check whether a Numpy array contains a specified row. 
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
  
# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True


In [12]:
#Q3. Write a Pandas code to create and display a DataFrame from a specified dictionary data which has the index labels
import pandas as pd
  
# dictionary with list object in values
details = {
    'Name' : ['Atishara', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [20, 21, 22, 21],
    'University' : ['SIRT', 'JNU', 'DU', 'BHU'],
}
  
# creating a Dataframe object 
df = pd.DataFrame(details)
  
df

Name  Age University
0   Atishara   20       SIRT
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU

In [13]:
#Q. 4.Write a pandas code to create DataFrame from dict of narray/lists
import pandas as pd
 
# initialise data of lists.
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df )

  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19


In [14]:
#Q. 5. Write a pandas code to create Pandas dataframe using list of lists
import pandas as pd
 
# initialize list of lists
data = [['Tia', 10], ['Shreya', 15], ['Atishara', 20]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Name', 'Age'])
 
# print dataframe.
print(df )

       Name  Age
0       Tia   10
1    Shreya   15
2  Atishara   20
